import fs from 'node:fs';
import path from 'node:path';
import { randomInt, randomUUID } from 'node:crypto';
import Launchpad from '../../Launchpad';

type MissionBuildPayload = {
    mission_name?: unknown;
    map_suffix?: unknown;
    author?: unknown;
    network_type?: unknown;
    generate_scripting_environment?: unknown;
    game_type?: unknown;
};

type MissionBuildResponse = {
    status: number;
    warnings: string[];
    messages: string[];
    mission_path?: string;
    mission_id?: string;
    error?: string;
};

type LaunchpadSettings = {
    arma3_profile_path: string;
    default_author: string;
};

const MANAGED_MISSIONS_FILE = 'managed_missions.json';
const PROFILE_MISSION_SYMLINK_SUBDIR = 'A3Launchpad_missions';

const EXT_TEMPLATE: Record<string, unknown> = {
    header: { gameType: 'CTI', minPlayers: 1, maxPlayers: 64 },
    difficultyOverride: { tacticalPing: 0 },
    cba_settings_hasSettingsFile: 0,
    saving: 0,
    taskManagement_markers3D: 1,
    allowSubordinatesTakeWeapons: 1,
    respawn: 3,
    respawnButton: 1,
    respawnDelay: 0,
    respawnVehicleDelay: 120,
    reviveMode: 2,
    reviveUnconsciousStateMode: 2,
    briefing: 0,
    debriefing: 0,
    skipLobby: 0,
    disabledAI: 1,
    aiKills: 1,
    enableDebugConsole: 1,
    enableTeamSwitch: 0,
    joinUnassigned: 1,
    onCheat: 'hint str _this',
    forceRotorLibSimulation: 1,
    corpseManagerMode: 1,
    corpseLimit: 25,
    corpseRemovalMinTime: 300,
    corpseRemovalMaxTime: 1200,
    weaponholderManagerMode: 3,
    weaponholderLimit: 25,
    weaponholderRemovalMinTime: 120,
    weaponholderRemovalMaxTime: 300,
    wreckManagerMode: 1,
    wreckLimit: 5,
    wreckRemovalMinTime: 300,
    wreckRemovalMaxTime: 300,
    disposalCheckPeriod: 30,
    minPlayerDistance: [50, 60, 70, 300, 120, 60],
};

const EVENT_SCRIPTS: Array<{ name: string; params?: string[] }> = [
    { name: 'init.sqf' },
    { name: 'init3DEN.sqf' },
    { name: 'initIntro.sqf' },
    { name: 'initPlayerLocal.sqf', params: ['_player', '_didJIP'] },
    { name: 'initPlayerServer.sqf', params: ['_playerUnit', '_didJIP'] },
    { name: 'initServer.sqf' },
    { name: 'onPlayerKilled.sqf', params: ['_oldUnit', '_killer', '_respawn', '_respawnDelay'] },
    { name: 'onPlayerRespawn.sqf', params: ['_newUnit', '_oldUnit', '_respawn', '_respawnDelay'] },
    { name: 'exit.sqf', params: ['_endType'] },
    { name: 'missionFlow.fsm' },
    { name: 'onFlare.sqs', params: ['_colorRGB', '_shooter', '_projectile', '_instigator'] },
    { name: 'teamSwitchScript.sqs', params: ['_oldUnit', '_newUnit'] },
];

function fail(error: string): MissionBuildResponse {
    return { status: 1, warnings: [], messages: [], error };
}

function readSettings(settingsFile: string): LaunchpadSettings {
    const defaults: LaunchpadSettings = { arma3_profile_path: '', default_author: '' };
    try {
        const raw = JSON.parse(fs.readFileSync(settingsFile, 'utf8')) as Record<string, unknown>;
        return {
            arma3_profile_path:
                typeof raw.arma3_profile_path === 'string' ? raw.arma3_profile_path.trim() : '',
            default_author: typeof raw.default_author === 'string' ? raw.default_author.trim() : '',
        };
    } catch {
        return defaults;
    }
}

function validateMissionToken(part: string, label: string): string | null {
    const s = part.trim();
    if (!s) return `${label} cannot be empty.`;
    if (s === '.' || s === '..') return `${label} is not a valid folder name.`;
    if (s.includes('/') || s.includes('\\') || s.includes('\0')) {
        return `${label} cannot contain path separators.`;
    }
    return null;
}

function profileSymlinkPath(profilePath: string, missionType: 'sp' | 'mp', missionFullname: string): string {
    const folder = missionType === 'sp' ? 'missions' : 'mpmissions';
    return path.join(profilePath, folder, PROFILE_MISSION_SYMLINK_SUBDIR, missionFullname);
}

function formatExtValue(value: unknown): string {
    if (typeof value === 'string') return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
    if (Array.isArray(value)) return `{ ${value.map((v) => formatExtValue(v)).join(', ')} }`;
    return String(value);
}

function generateDescriptionExt(projectPath: string, params: Record<string, unknown>, author: string): void {
    const generationTime = new Date().toISOString().replace('T', ' ').slice(0, 19);
    let out = `/**\n    --This file was generated by A3 Launchpad.--\n    Author: ${author}\n    File: Description.ext\n    Time: ${generationTime}\n*/\n`;
    const header = (params.header ?? {}) as Record<string, unknown>;
    const difficultyOverride = (params.difficultyOverride ?? {}) as Record<string, unknown>;
    out += `class Header {\n${Object.entries(header).map(([k, v]) => `    ${k} = ${formatExtValue(v)};`).join('\n')}\n}\n\n`;
    out += `class DifficultyOverride {\n${Object.entries(difficultyOverride).map(([k, v]) => `    ${k} = ${formatExtValue(v)};`).join('\n')}\n}\n\n`;
    for (const [k, v] of Object.entries(params)) {
        if (k === 'header' || k === 'difficultyOverride') continue;
        out += `${k} = ${formatExtValue(v)};\n`;
    }
    fs.writeFileSync(path.join(projectPath, 'Description.ext'), out, 'utf8');
}

function generateMissionSqm(projectPath: string, author: string): void {
    const randomSeed = randomInt(1, 2_147_483_647);
    const sqm = `version=54;\nclass EditorData\n{\n\tmoveGridStep=1;\n};\nbinarizationWanted=0;\nsourceName="default";\nclass AddonsMetaData\n{\n};\nrandomSeed=${randomSeed};\nclass ScenarioData\n{\n\tauthor="${author}";\n};\n`;
    fs.writeFileSync(path.join(projectPath, 'mission.sqm'), sqm, 'utf8');
}

function generateScriptingEnvironment(projectPath: string): void {
    for (const script of EVENT_SCRIPTS) {
        const prefix =
            script.name.toLowerCase().endsWith('.sqf') && script.params?.length
                ? `params [${script.params.map((p) => `"${p}"`).join(', ')}];\n`
                : '';
        fs.writeFileSync(path.join(projectPath, script.name), prefix, 'utf8');
    }
    const functionsPath = path.join(projectPath, 'functions', 'example_library');
    fs.mkdirSync(functionsPath, { recursive: true });
    fs.writeFileSync(path.join(functionsPath, 'fn_helloWorld.sqf'), 'systemChat "Hello World";\n', 'utf8');
}

function readManagedMissions(pathToFile: string): Record<string, unknown> {
    try {
        const raw = JSON.parse(fs.readFileSync(pathToFile, 'utf8'));
        return raw && typeof raw === 'object' ? (raw as Record<string, unknown>) : {};
    } catch {
        return {};
    }
}

function writeManagedMissions(pathToFile: string, data: Record<string, unknown>): void {
    fs.mkdirSync(path.dirname(pathToFile), { recursive: true });
    const tmpPath = `${pathToFile}.tmp`;
    fs.writeFileSync(tmpPath, `${JSON.stringify(data, null, 4)}\n`, 'utf8');
    fs.renameSync(tmpPath, pathToFile);
}

/**
 * @param _ctx - The Launchpad instance,
 * @param _event - The IpcMainInvokeEvent instance
 * @param args - The arguments object
 * @param args.mission_name - The name of the mission
 * @param args.map_suffix - The map suffix
 * @param args.author - The author of the mission
 * @param args.network_type - The network type
 * @param args.generate_scripting_environment - Whether to generate a scripting environment
 * @param args.game_type - The game type
 * @param args 
 * @returns The mission build response
 * Example Payload:
 * {
 *     mission_name: "My Mission",
 *     map_suffix: "my_map",
 *     author: "John Doe",
 *     network_type: "Multiplayer",
 *     generate_scripting_environment: true,
 *     game_type: "CTI"
 * }
 */
export async function handleMissionBuildRequest(
    ctx: Launchpad,
    _event: Electron.IpcMainInvokeEvent,
    args: unknown
): Promise<MissionBuildResponse> {
    const body = (args ?? {}) as MissionBuildPayload;
    const missionName = String(body.mission_name ?? '').trim();
    const mapSuffix = String(body.map_suffix ?? '').trim();
    const dataDir = ctx.dataDir;
    const settings = readSettings(ctx.settingsFile);
    const author = String(body.author ?? '').trim() || settings.default_author;

    const missionNameErr = validateMissionToken(missionName, 'Mission name');
    if (missionNameErr) return fail(missionNameErr);
    const mapSuffixErr = validateMissionToken(mapSuffix, 'Map suffix');
    if (mapSuffixErr) return fail(mapSuffixErr);
    if (!author) return fail('Author cannot be empty.');
    if (author.includes('/') || author.includes('\\') || author.includes('\0')) {
        return fail('Author cannot contain path separators.');
    }

    const profilePathRaw = settings.arma3_profile_path.trim();
    if (!profilePathRaw) return fail('Arma 3 profile folder is not configured in Settings.');
    const profilePath = path.resolve(profilePathRaw);
    if (!fs.existsSync(profilePath) || !fs.statSync(profilePath).isDirectory()) {
        return fail('Arma profile path must be an existing folder.');
    }

    const network = String(body.network_type ?? 'Multiplayer').trim();
    const missionType: 'sp' | 'mp' = network === 'Singleplayer' ? 'sp' : 'mp';
    const missionFullname = `${missionName}.${mapSuffix}`;
    const projectsRoot = path.join(dataDir, 'mission_projects');
    const projectPath = path.join(projectsRoot, missionFullname);
    if (fs.existsSync(projectPath)) {
        return fail(`A mission project folder already exists at ${projectPath}.`);
    }

    const warnings: string[] = [];
    try {
        fs.mkdirSync(projectPath, { recursive: true });
        const symlinkPath = profileSymlinkPath(profilePath, missionType, missionFullname);
        fs.mkdirSync(path.dirname(symlinkPath), { recursive: true });
        try {
            fs.symlinkSync(projectPath, symlinkPath, 'junction');
        } catch (err) {
            warnings.push(`Could not create Arma profile symlink (${String(err)}).`);
        }

        const gameType = String(body.game_type ?? 'Unknown').trim();
        const descriptionExtParams: Record<string, unknown> = {
            ...EXT_TEMPLATE,
            author,
            onLoadName: missionFullname,
            briefingName: missionFullname,
            loadScreen: missionFullname,
            header: {
                ...((EXT_TEMPLATE.header ?? {}) as Record<string, unknown>),
                ...(gameType && gameType !== 'Unknown' ? { gameType } : {}),
            },
        };

        generateMissionSqm(projectPath, author);
        generateDescriptionExt(projectPath, descriptionExtParams, author);
        if (Boolean(body.generate_scripting_environment)) {
            generateScriptingEnvironment(projectPath);
        }

        const managedMissionsPath = path.join(dataDir, MANAGED_MISSIONS_FILE);
        const allMissions = readManagedMissions(managedMissionsPath);
        const missionId = randomUUID();
        allMissions[missionId] = {
            name: missionName,
            map_suffix: mapSuffix,
            description: `Mission ${missionFullname}`,
            author,
            mission_type: missionType,
            generate_scripting_environment: Boolean(body.generate_scripting_environment),
            project_path: projectPath,
            profile_path: profilePath,
            github_integration: false,
            launch_mods: [],
        };
        writeManagedMissions(managedMissionsPath, allMissions);

        return {
            status: 0,
            warnings,
            messages: [
                `Mission registered as managed id ${missionId}.`,
                `Arma folder name: ${missionFullname}`,
            ],
            mission_path: projectPath,
            mission_id: missionId,
        };
    } catch (err) {
        return fail(err instanceof Error ? err.message : 'Mission build request failed.');
    }
}